FROM python:3.9-slim

WORKDIR /app
COPY . .

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg libsndfile1 \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir \
        flask \
        gunicorn \
        transformers \
        torch \
        torchvision \
        torchaudio \
        pillow \
        soundfile \
        requests

ENV PYTHONUNBUFFERED=1

CMD ["gunicorn", "--workers", "2", "--bind", "0.0.0.0:5004", "translation_service:app"]